/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_learnncode_learnndk_JniFunction */

#ifndef _Included_com_learnncode_learnndk_JniFunction
#define _Included_com_learnncode_learnndk_JniFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_learnncode_learnndk_JniFunction
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_learnncode_learnndk_JniFunction_getJniString
  (JNIEnv *, jclass);

/*
 * Class:     com_learnncode_learnndk_JniFunction
 * Method:    addNumber
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_learnncode_learnndk_JniFunction_addNumber
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_learnncode_learnndk_JniFunction
 * Method:    getBooleanValue
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_learnncode_learnndk_JniFunction_getBooleanValue
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_learnncode_learnndk_JniFunction
 * Method:    getByteValue
 * Signature: (Ljava/lang/Byte;)Ljava/lang/Byte;
 */
JNIEXPORT jobject JNICALL Java_com_learnncode_learnndk_JniFunction_getByteValue
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_learnncode_learnndk_JniFunction
 * Method:    getShortValue
 * Signature: (Ljava/lang/Short;)S
 */
JNIEXPORT jshort JNICALL Java_com_learnncode_learnndk_JniFunction_getShortValue
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_learnncode_learnndk_JniFunction
 * Method:    getLongValue
 * Signature: (Ljava/lang/Long;)J
 */
JNIEXPORT jlong JNICALL Java_com_learnncode_learnndk_JniFunction_getLongValue
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_learnncode_learnndk_JniFunction
 * Method:    getFloatValue
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_learnncode_learnndk_JniFunction_getFloatValue
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_learnncode_learnndk_JniFunction
 * Method:    getDoubleValue
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_learnncode_learnndk_JniFunction_getDoubleValue
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_learnncode_learnndk_JniFunction
 * Method:    doSomeThing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_learnncode_learnndk_JniFunction_doSomeThing
  (JNIEnv *, jclass);

/*
 * Class:     com_learnncode_learnndk_JniFunction
 * Method:    getIntArray
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_learnncode_learnndk_JniFunction_getIntArray
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_learnncode_learnndk_JniFunction
 * Method:    getIntList
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_learnncode_learnndk_JniFunction_getIntList
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_learnncode_learnndk_JniFunction
 * Method:    sumIntList
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_learnncode_learnndk_JniFunction_sumIntList
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_learnncode_learnndk_JniFunction
 * Method:    getImgGreyPixels
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_learnncode_learnndk_JniFunction_getImgGreyPixels
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
