/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// void __usercall sub_550(int a1@<ebx>);
// int __cdecl __cxa_atexit(_DWORD, _DWORD, _DWORD); weak
// int __cdecl __cxa_finalize(_DWORD); weak
int sub_590();
int sub_5C0(); // weak
int __cdecl sub_5E0(int a1);
void __noreturn sub_620();
void sub_640();
int __cdecl Java_com_learnncode_learnndk_JniFunction_getJniString(int a1);
int __cdecl Java_com_learnncode_learnndk_JniFunction_addNumber(int a1, int a2, int a3, int a4);
int __cdecl Java_com_learnncode_learnndk_JniFunction_sumIntList(int a1, int a2, int a3);
int __cdecl Java_com_learnncode_learnndk_JniFunction_getIntList(int a1, int a2, int a3);
int __cdecl Java_com_learnncode_learnndk_JniFunction_getImgGreyPixels(int a1, int a2, int a3, unsigned int a4, int a5);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_635; // weak
__int128 xmmword_C10 = 0x1000000010000000100000001LL; // weak
void *off_2000 = &off_2000; // weak
// extern _UNKNOWN _stack_chk_guard; weak


//----- (00000550) --------------------------------------------------------
void __usercall sub_550(int a1@<ebx>)
{
  int v1; // ST00_4

  v1 = *(_DWORD *)(a1 + 4);
  JUMPOUT(__CS__, *(_DWORD *)(a1 + 8));
}

//----- (00000590) --------------------------------------------------------
int sub_590()
{
  return __cxa_finalize(&off_2000);
}
// 580: using guessed type int __cdecl __cxa_finalize(_DWORD);
// 2000: using guessed type void *off_2000;

//----- (000005E0) --------------------------------------------------------
int __cdecl sub_5E0(int a1)
{
  return __cxa_atexit(sub_5C0, a1, &off_2000);
}
// 560: using guessed type int __cdecl __cxa_atexit(_DWORD, _DWORD, _DWORD);
// 5C0: using guessed type int sub_5C0();
// 2000: using guessed type void *off_2000;

//----- (00000620) --------------------------------------------------------
void __noreturn sub_620()
{
  JUMPOUT(loc_635);
}

//----- (00000640) --------------------------------------------------------
void sub_640()
{
  ;
}

//----- (00000650) --------------------------------------------------------
int __cdecl Java_com_learnncode_learnndk_JniFunction_getJniString(int a1)
{
  return (*(int (__cdecl **)(int, const char *))(*(_DWORD *)a1 + 668))(a1, "Hello Android NDK");
}

//----- (00000690) --------------------------------------------------------
int __cdecl Java_com_learnncode_learnndk_JniFunction_addNumber(int a1, int a2, int a3, int a4)
{
  return a3 + a4;
}

//----- (000006A0) --------------------------------------------------------
int __cdecl Java_com_learnncode_learnndk_JniFunction_sumIntList(int a1, int a2, int a3)
{
  int v3; // esi
  int v4; // eax
  int v5; // edi
  unsigned int v6; // edx
  const __m128i *v7; // edx
  __m128i v8; // xmm0
  unsigned int v9; // edi
  __m128i v10; // xmm1
  __m128i v11; // xmm1
  __m128i v12; // xmm0
  _DWORD *v13; // ecx
  int v14; // esi

  v3 = (*(int (__cdecl **)(int, int))(*(_DWORD *)a1 + 684))(a1, a3);
  v4 = (*(int (__cdecl **)(int, int, _DWORD))(*(_DWORD *)a1 + 748))(a1, a3, 0);
  v5 = 0;
  if ( v3 > 0 )
  {
    if ( (unsigned int)v3 < 8 )
    {
      v6 = 0;
LABEL_8:
      v13 = (_DWORD *)(v4 + 4 * v6);
      v14 = v3 - v6;
      do
      {
        v5 += *v13;
        ++v13;
        --v14;
      }
      while ( v14 );
      goto LABEL_10;
    }
    v6 = 0;
    if ( !(v3 & 0xFFFFFFF8) )
      goto LABEL_8;
    v7 = (const __m128i *)(v4 + 16);
    v8 = 0LL;
    v9 = v3 & 0xFFFFFFF8;
    v10 = 0LL;
    do
    {
      v8 = _mm_add_epi32(v8, _mm_loadu_si128(v7 - 1));
      v10 = _mm_add_epi32(v10, _mm_loadu_si128(v7));
      v7 += 2;
      v9 -= 8;
    }
    while ( v9 );
    v11 = _mm_add_epi32(v10, v8);
    v12 = _mm_add_epi32(_mm_shuffle_epi32(v11, 78), v11);
    v5 = _mm_cvtsi128_si32(_mm_hadd_epi32(v12, v12));
    v6 = v3 & 0xFFFFFFF8;
    if ( v3 != (v3 & 0xFFFFFFF8) )
      goto LABEL_8;
  }
LABEL_10:
  (*(void (__cdecl **)(int, int, int, _DWORD))(*(_DWORD *)a1 + 780))(a1, a3, v4, 0);
  return v5;
}

//----- (00000780) --------------------------------------------------------
int __cdecl Java_com_learnncode_learnndk_JniFunction_getIntList(int a1, int a2, int a3)
{
  int v3; // edi
  unsigned int v4; // eax
  unsigned int v5; // edx
  const __m128i *v6; // edx
  __m128i *v7; // edi
  __m128i v8; // xmm0
  unsigned int v9; // ecx
  __m128i v10; // xmm2
  _DWORD *v11; // eax
  __int32 *v12; // ecx
  int v13; // edi
  int v14; // eax
  unsigned int v15; // edi
  int v16; // eax
  int v17; // ecx
  int v18; // edi
  int result; // eax
  int v20; // [esp+0h] [ebp-2Ch]
  int v21; // [esp+4h] [ebp-28h]
  __m128i *v22; // [esp+8h] [ebp-24h]
  unsigned int v23; // [esp+Ch] [ebp-20h]
  unsigned int v24; // [esp+10h] [ebp-1Ch]
  int *v25; // [esp+14h] [ebp-18h]
  int v26; // [esp+18h] [ebp-14h]

  v25 = (int *)&_stack_chk_guard;
  v3 = (*(int (__cdecl **)(int, int))(*(_DWORD *)a1 + 684))(a1, a3);
  v4 = (*(int (__cdecl **)(int, int, _DWORD))(*(_DWORD *)a1 + 748))(a1, a3, 0);
  v22 = (__m128i *)((char *)&v20 - ((4 * v3 + 15) & 0xFFFFFFF0));
  v23 = v3;
  if ( v3 > 0 )
  {
    v5 = 0;
    if ( v23 < 8 )
      goto LABEL_15;
    if ( !(v23 & 0xFFFFFFF8) )
      goto LABEL_15;
    v24 = v23 & 0xFFFFFFF8;
    if ( (unsigned int)v22 < v4 + 4 * v23 && v4 < (unsigned int)v22 + 4 * v23 )
      goto LABEL_15;
    v6 = (const __m128i *)(v4 + 16);
    v7 = v22 + 1;
    v8 = _mm_load_si128((const __m128i *)&xmmword_C10);
    v9 = v24;
    do
    {
      v10 = _mm_add_epi32(_mm_loadu_si128(v6), v8);
      _mm_storeu_si128(v7 - 1, _mm_add_epi32(_mm_loadu_si128(v6 - 1), v8));
      _mm_storeu_si128(v7, v10);
      v6 += 2;
      v7 += 2;
      v9 -= 8;
    }
    while ( v9 );
    v5 = v24;
    if ( v23 != v24 )
    {
LABEL_15:
      v11 = (_DWORD *)(v4 + 4 * v5);
      v12 = &v22->m128i_i32[v5];
      v13 = v23 - v5;
      do
      {
        *v12 = *v11 + 1;
        ++v11;
        ++v12;
        --v13;
      }
      while ( v13 );
    }
  }
  v14 = *(_DWORD *)a1;
  v15 = v23;
  v25 = (int *)v23;
  v24 = a1;
  v16 = (*(int (__cdecl **)(int, unsigned int))(v14 + 716))(a1, v23);
  v17 = *(_DWORD *)a1;
  v24 = (unsigned int)v22;
  v23 = v15;
  v18 = v16;
  v22 = 0;
  v21 = v16;
  v20 = a1;
  (*(void (__cdecl **)(int, int, _DWORD, unsigned int, unsigned int))(v17 + 844))(a1, v16, 0, v23, v24);
  result = *v25;
  if ( *v25 == v26 )
    result = v18;
  return result;
}
// C10: using guessed type __int128 xmmword_C10;

//----- (000008E0) --------------------------------------------------------
int __cdecl Java_com_learnncode_learnndk_JniFunction_getImgGreyPixels(int a1, int a2, int a3, unsigned int a4, int a5)
{
  int v5; // edi
  unsigned int v6; // ebx
  __int64 v7; // xmm0_8
  __int64 v8; // xmm1_8
  __int64 v9; // xmm2_8
  __m128i v10; // xmm5
  __m128d v11; // xmm6
  __m128d v12; // xmm7
  int v13; // edx
  __m128i *v14; // ecx
  unsigned int v15; // edi
  unsigned int v16; // edi
  const __m128i *v17; // eax
  __m128i *v18; // ebx
  __m128i v19; // xmm0
  __m128i v20; // xmm5
  __m128d v21; // xmm1
  __m128 v22; // xmm7
  __m128 v23; // xmm4
  __m128d v24; // xmm3
  __m128d v25; // xmm6
  __m128 v26; // xmm5
  __m128i v27; // xmm3
  int v28; // eax
  double v29; // xmm3_8
  int v30; // eax
  int v31; // edi
  int v32; // eax
  int v33; // ecx
  int v34; // edi
  int result; // eax
  int v36; // [esp+0h] [ebp-9Ch]
  __m128i *v37; // [esp+Ch] [ebp-90h]
  unsigned int v38; // [esp+10h] [ebp-8Ch]
  int v39; // [esp+14h] [ebp-88h]
  unsigned int v40; // [esp+18h] [ebp-84h]
  int v41; // [esp+1Ch] [ebp-80h]
  int v42; // [esp+20h] [ebp-7Ch]
  int v43; // [esp+24h] [ebp-78h]
  int *v44; // [esp+28h] [ebp-74h]
  unsigned int v45; // [esp+2Ch] [ebp-70h]
  unsigned int v46; // [esp+30h] [ebp-6Ch]
  unsigned int v47; // [esp+34h] [ebp-68h]
  __int64 v48; // [esp+38h] [ebp-64h]
  __int64 v49; // [esp+40h] [ebp-5Ch]
  __int64 v50; // [esp+48h] [ebp-54h]
  __m128d v51; // [esp+50h] [ebp-4Ch]
  __m128i v52; // [esp+60h] [ebp-3Ch]
  __m128d v53; // [esp+70h] [ebp-2Ch]
  __int32 *v54; // [esp+80h] [ebp-1Ch]
  int v55; // [esp+84h] [ebp-18h]
  int v56; // [esp+88h] [ebp-14h]

  v44 = (int *)&_stack_chk_guard;
  v5 = (*(int (__cdecl **)(int, int))(*(_DWORD *)a1 + 684))(a1, a3);
  v42 = 8168;
  v39 = (*(int (__cdecl **)(int, int, _DWORD))(*(_DWORD *)a1 + 748))(a1, a3, 0);
  v43 = v5;
  v37 = (__m128i *)((char *)&v36 - ((4 * v5 + 15) & 0xFFFFFFF0));
  if ( a5 > 0 )
  {
    v6 = a4;
    v40 = a4 & 0xFFFFFFFC;
    v47 = 4 * a4;
    v41 = 0;
    v7 = *(__int64 *)(v42 - 4984);
    v8 = *(__int64 *)(v42 - 4976);
    v9 = *(__int64 *)(v42 - 4968);
    v10 = _mm_load_si128((const __m128i *)(v42 - 5064));
    v11 = *(__m128d *)(v42 - 5048);
    v12 = *(__m128d *)(v42 - 5032);
    v53 = *(__m128d *)(v42 - 5016);
    _mm_store_si128(&v52, _mm_load_si128((const __m128i *)(v42 - 5000)));
    v13 = v39;
    v14 = v37;
    v50 = v7;
    v49 = v8;
    v51 = v11;
    v48 = v9;
    do
    {
      if ( (signed int)v6 > 0 )
      {
        v15 = 0;
        if ( v6 < 4 )
          goto LABEL_17;
        if ( !v40 )
          goto LABEL_17;
        v38 = v6 * v41 + v6;
        v45 = v6 * v41;
        v46 = (unsigned int)v37 + 4 * v6 * v41;
        if ( v46 < v39 + 4 * v38 )
        {
          v38 = (unsigned int)v37 + 4 * v38;
          if ( v39 + 4 * v45 < v38 )
            goto LABEL_17;
        }
        v16 = v40;
        v17 = (const __m128i *)v13;
        v18 = v14;
        v19 = v10;
        do
        {
          v20 = _mm_loadu_si128(v17);
          v21 = v12;
          v22 = _mm_cvtepi32_ps(_mm_and_si128(_mm_srli_epi32(v20, 0x10u), v19));
          v23 = _mm_cvtepi32_ps(_mm_and_si128(_mm_srli_epi32(v20, 8u), v19));
          v24 = _mm_add_pd(_mm_mul_pd(_mm_cvtps_pd(v23), v21), _mm_mul_pd(_mm_cvtps_pd(v22), v51));
          v25 = _mm_cvtps_pd(_mm_movehl_ps(v22, v22));
          v12 = v21;
          v26 = _mm_cvtepi32_ps(_mm_and_si128(v20, v19));
          v27 = _mm_unpacklo_epi64(
                  _mm_cvttpd_epi32(_mm_add_pd(_mm_mul_pd(_mm_cvtps_pd(v26), v53), v24)),
                  _mm_cvttpd_epi32(
                    _mm_add_pd(
                      _mm_mul_pd(_mm_cvtps_pd(_mm_movehl_ps(v26, v26)), v53),
                      _mm_add_pd(_mm_mul_pd(_mm_cvtps_pd(_mm_movehl_ps(v23, v23)), v21), _mm_mul_pd(v25, v51)))));
          _mm_storeu_si128(
            v18,
            _mm_or_si128(_mm_or_si128(_mm_or_si128(_mm_slli_epi32(v27, 0x10u), v27), _mm_slli_epi32(v27, 8u)), v52));
          ++v18;
          ++v17;
          v16 -= 4;
        }
        while ( v16 );
        v6 = a4;
        v15 = v40;
        v10 = v19;
        v7 = v50;
        v8 = v49;
        v9 = v48;
        if ( v40 != a4 )
        {
LABEL_17:
          do
          {
            v28 = *(_DWORD *)(v13 + 4 * v15);
            v29 = (float)(unsigned __int8)*(_DWORD *)(v13 + 4 * v15) * *(double *)&v9
                + (float)BYTE1(v28) * *(double *)&v8
                + (float)(unsigned __int8)(*(_DWORD *)(v13 + 4 * v15) >> 16) * *(double *)&v7;
            v14->m128i_i32[v15] = ((signed int)v29 << 8) | (signed int)v29 | ((signed int)v29 << 16) | 0xFF000000;
            v6 = a4;
            ++v15;
          }
          while ( a4 != v15 );
        }
      }
      v14 = (__m128i *)((char *)v14 + v47);
      v13 += v47;
      ++v41;
    }
    while ( v41 != a5 );
  }
  v30 = *(_DWORD *)a1;
  v31 = v43;
  v55 = v43;
  v54 = (__int32 *)a1;
  v32 = (*(int (__cdecl **)(int, int))(v30 + 716))(a1, v43);
  v33 = *(_DWORD *)a1;
  v54 = (__int32 *)v37;
  HIDWORD(v53.m128d_f64[1]) = v31;
  v34 = v32;
  *(_QWORD *)((char *)v53.m128d_f64 + 4) = (unsigned int)v32;
  LODWORD(v53.m128d_f64[0]) = a1;
  (*(void (__cdecl **)(int, int, _DWORD, _DWORD, __m128i *))(v33 + 844))(a1, v32, 0, HIDWORD(v53.m128d_f64[1]), v37);
  result = *v44;
  if ( *v44 == v56 )
    result = v34;
  return result;
}

// ALL OK, 10 function(s) have been successfully decompiled
